[package]
name = "s3_bucket_perma_link"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "s3_bucket_perma_link"

[dependencies]
getset = "0.1.2"
derive-new = "0.5.9"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1.14"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
anyhow = { version = "1.0.75", features = ["backtrace"] }
thiserror = "1.0"
backtrace = "0.3.69"
actix-web = "4.4.0"
tracing-actix-web = "0.7.6"
config = "0.13.3"
serde = "1.0.188"
serde_json = "1.0.107"
minio-rsc = "0.1.7"
sentry = { version = "0.31.6", features = ["anyhow", "debug-images", "backtrace"] }
secrecy = { version = "0.8.0", features = ["serde"] }
time = "0.3.28"

[profile.release]
lto = true
codegen-units = 1
debug = true